# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_details',
            name='cust_dob',
            field=models.DateField(auto_now_add=True, verbose_name='cust_dob'),
        ),
    ]
